name: deno basic ci

on:
  - push

jobs:
  deno_fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6
      - uses: denoland/setup-deno@v1
      - run: deno task fmt:check
  deno_check:
    runs-on: ubuntu-latest
    needs: deno_fmt
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6
      - uses: denoland/setup-deno@v1
      - run: deno task check
  deno_lint:
    runs-on: ubuntu-latest
    needs: deno_fmt
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6
      - uses: denoland/setup-deno@v1
      - run: deno task lint
